version: '3.8'

services:
  db:
    image: postgres:13.3-buster
    env_file: .env.prod.db
    volumes:
      - pgdata:/var/lib/postgresql/data
  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile.prod
    command: gunicorn djangotemplate.config.wsgi:application --bind 0.0.0.0:8000
    env_file: .env.prod
    expose:
      - 8000
    volumes:
      - staticfiles:/home/app/srv/staticfiles
    depends_on:
      - db
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    volumes:
      - staticfiles:/srv/staticfiles
    ports:
      - 80
    depends_on:
      - backend
volumes:
  pgdata:
  staticfiles:
