version: '3.8'

services:
  db:
    image: postgres:13.3-buster
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PASSWORD:
      POSTGRES_DB: djangotemplate
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432
  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    command: sh -c 'while true; do ./manage.py runserver 0.0.0.0:8000; sleep 1; done'
    env_file: .env.dev
    ports:
      - 8000
    volumes:
      - venv:/venv
      - ./app/:/srv
    depends_on:
      - db
    stdin_open: true
    tty: true
  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - 8025
volumes:
  pgdata:
  venv:
